doctrine_migrations:
    storage:
        table_storage:
            table_name:     'migrations'
    migrations_paths:
        DoctrineMigrations: '%kernel.project_dir%/migrations'
    enable_profiler:        '%kernel.debug%'
