security:
    enable_authenticator_manager: true

    providers:
        user_provider:
            entity:
                class:  'App\Entity\User'

    firewalls:
        dev:
            pattern:    '^/(_(profiler|wdt)|css|images|js)/'
            security:   false

        user_password:
            pattern:                '^/auth$'
            provider:               'user_provider'
            lazy:                   true
            stateless:              true
            custom_authenticator:   'App\Security\Authenticator\PasswordAuthenticator'

        user_jwt_refresh:
            pattern:                '^/auth/refresh$'
            provider:               'user_provider'
            lazy:                   true
            stateless:              true
            custom_authenticator:   'App\Security\Authenticator\RefreshAuthenticator'

        user_jwt:
            provider:               'user_provider'
            lazy:                   true
            stateless:              true
            custom_authenticator:   'App\Security\Authenticator\TokenAuthenticator'
