monolog:
    handlers:
        main:
            level:  'debug'
        app:
            level:  'debug'
        console:
            level:  'debug'
        doctrine:
            level:  'debug'
        event:
            level:  'debug'
        exception:
            level:  'debug'
        failed_response:
            level:  'debug'
        php:
            level:  'debug'
        request:
            level:  'debug'
