parameters:
    # Common
    app.base_url:   '%env(ROUTER_BASE_URL)%'
    app.sitename:   'Demo App'

    # Json Web Token parameters
    app.jwt.access_token_ttl:   '%env(int:JWT_ACCESS_TOKEN_TTL)%'
    app.jwt.refresh_token_ttl:  '%env(int:JWT_REFRESH_TOKEN_TTL)%'

    # Contacts
    app.contacts.available:
        - 'facebook'        # facebook.com/profile.php?id=* || facebook.com/*  || fb.com/*
        - 'instagram'       # instagram.com/*/
        - 'twitter'         # twitter.com/* || twitter.com/@*
        - 'linkedin'        # linkedin.com/in/* || linked.in/*
        - 'vk'              # vk.com/* || vk.com/id* || vk.me/* || vk.me/id*
        - 'medium'          # *.medium.com || medium.com/* || medium.com/@*
        - 'github'          # github.com/*/
        - 'bitbucket'       # bitbucket.org/*/ || bitbucket.com/*/
        - 'flickr'          # flickr.com/people/*/ || flickr.com/photos/*/ || flickr.com/*/
        - 'behance'         # behance.net/*
        - 'dribbble'        # dribbble.com/*
        - 'skype'           # *
        - 'telegram'        # t.me/*

    app.contacts.formats:
        facebook:       'https://facebook.com/%s'
        instagram:      'https://instagram.com/%s/'
        twitter:        'https://twitter.com/%s'
        linkedin:       'https://linkedin.com/in/%s'
        vk:             'https://vk.com/%s'
        medium:         'https://medium.com/@%s'
        github:         'https://github.com/%s/'
        bitbucket:      'https://bitbucket.org/%s/'
        flickr:         'https://flickr.com/people/%s/'
        behance:        'https://behance.net/%s'
        dribbble:       'https://dribbble.com/%s'
        skype:          'skype:%s'
        telegram:       'https://t.me/%s'

    app.contacts.regex:
        facebook:     '^(?:(?:.+)(?:com))*(?:\/)*(?:profile\.php\?id=)*(\w+)(?:.*)$'
        instagram:    '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        twitter:      '^(?:(?:.+)(?:com))*(?:\/)*(?:@)*(\w+)(?:.*)$'
        linkedin:     '^(?:(?:.+)(?:com|in))*(?:\/)*(?:in\/)*(\w+)(?:.*)$'
        vk:           '^(?:(?:.+)(?:com|me|ru))*(?:\/)*(\w+)(?:.*)$'
        medium:       '^(?:(?:.+)(?:com))*(?:\/)*(?:@)*(\w+)(?:.*)$'
        github:       '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        bitbucket:    '^(?:(?:.+)(?:com|org))*(?:\/)*(\w+)(?:.*)$'
        flickr:       '^(?:(?:.+)(?:com))*(?:\/(?:people|photos))*(?:\/)*(\w+)(?:.*)$'
        behance:      '^(?:(?:.+)(?:com|net))*(?:\/)*(\w+)(?:.*)$'
        dribbble:     '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        skype:        '^(?:skype\:)*(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        telegram:     '^(?:(?:.+)(?:com|me))*(?:\/)*(\w+)(?:.*)$'

    # Blog posts config options
    app.blog_posts.restore_days_limit:   30

    # Users config options
    app.users.contacts: '%app.contacts.available%'

    app.users.enable_website:   true
    app.users.enable_phone:     true
    app.users.enable_city:      true
    app.users.enable_birthdate: true
    app.users.enable_contacts:  true

    app.users.restore_days_limit:   30
