parameters:
    # Json Web Token parameters
    app.jwt.access_token_ttl:   '%env(int:JWT_ACCESS_TOKEN_TTL)%'
    app.jwt.refresh_token_ttl:  '%env(int:JWT_REFRESH_TOKEN_TTL)%'

    # Contacts
    app.contacts.formats:
        facebook:       'https://facebook.com/%s'
        instagram:      'https://instagram.com/%s/'
        twitter:        'https://twitter.com/%s'
        linkedin:       'https://linkedin.com/in/%s'
        vk:             'https://vk.com/%s'
        medium:         'https://medium.com/@%s'
        github:         'https://github.com/%s/'
        bitbucket:      'https://bitbucket.org/%s/'
        flickr:         'https://flickr.com/people/%s/'
        behance:        'https://behance.net/%s'
        dribbble:       'https://dribbble.com/%s'
        skype:          'skype:%s'
        telegram:       'https://t.me/%s'

    app.contacts.regex:
        facebook:     '^(?:(?:.+)(?:com))*(?:\/)*(?:profile\.php\?id=)*(\w+)(?:.*)$'
        instagram:    '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        twitter:      '^(?:(?:.+)(?:com))*(?:\/)*(?:@)*(\w+)(?:.*)$'
        linkedin:     '^(?:(?:.+)(?:com|in))*(?:\/)*(?:in\/)*(\w+)(?:.*)$'
        vk:           '^(?:(?:.+)(?:com|me|ru))*(?:\/)*(\w+)(?:.*)$'
        medium:       '^(?:(?:.+)(?:com))*(?:\/)*(?:@)*(\w+)(?:.*)$'
        github:       '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        bitbucket:    '^(?:(?:.+)(?:com|org))*(?:\/)*(\w+)(?:.*)$'
        flickr:       '^(?:(?:.+)(?:com))*(?:\/(?:people|photos))*(?:\/)*(\w+)(?:.*)$'
        behance:      '^(?:(?:.+)(?:com|net))*(?:\/)*(\w+)(?:.*)$'
        dribbble:     '^(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        skype:        '^(?:skype\:)*(?:(?:.+)(?:com))*(?:\/)*(\w+)(?:.*)$'
        telegram:     '^(?:(?:.+)(?:com|me))*(?:\/)*(\w+)(?:.*)$'