parameters:
    # Directories
    app.dir.demo:       '%kernel.project_dir%/demo'
    app.dir.jwt_keys:   '%kernel.project_dir%/config/secrets/jwt'
    app.dir.langs:      '%kernel.project_dir%/langs'

    # Routing
    router.request_context.host:        '%env(ROUTER_HOST)%'
    router.request_context.scheme:      '%env(ROUTER_SCHEME)%'
    router.request_context.base_url:    '%env(ROUTER_BASE_URL)%'

services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Kernel.php'

    App\Controller\:
        resource:   '../src/Controller/'
        tags:
            - 'controller.service_arguments'

    App\EventListener\KernelEventListener:
        tags:
            -
                method:     'catchResponse'
                name:       'kernel.event_listener'
                event:      'kernel.response'
            -
                method:     'catchException'
                name:       'kernel.event_listener'
                event:      'kernel.exception'
